

export const actionTypes = {
    GET_OWN_FLASHCARDS:'GET_OWN_FLASHCARDS',
    EXPLORE_FLASHCARDS:'EXPLORE_FLASHCARDS',
    EDIT_FLASHCARD:"EDIT_FLASHCARD",
    EDIT_DESCRIPTION:'EDIT_DESCRIPTION',
    EDIT_URL:'EDIT_URL',
    EDIT_IS_DONE:'EDIT_IS_DONE',
  }